-- Database Schema Documentation
-- File: .ai-knowledge/20_database_schema.sql
--
-- Source of truth:
--   apps/api-medusa/src/modules/ai-personalization/models/*
--   apps/api-medusa/src/modules/ai-personalization/migrations/*
--   apps/ai-service/src/database/schema.py
--
-- Scope:
--   This file documents the custom AI Personalization tables that are
--   actually defined by the project. Core e-commerce tables such as product,
--   variant, cart, order and customer are managed by MedusaJS and are not
--   redefined here.
--
-- Important synchronization note:
--   customer_id, product_id, replaces_item_id and parent_job_id are stored as
--   text values in the custom module. They are logical references used by the
--   application code, not physical foreign keys, except where a constraint is
--   explicitly declared below.

-- =====================================================================
-- 1. AI PROFILE
-- =====================================================================
-- Used by:
--   apps/api-medusa/src/api/v1/ai-profile/route.ts
--
-- Behavior:
--   The route implements an upsert-like flow by customer_id. The schema does
--   not declare customer_id as UNIQUE, therefore uniqueness is enforced by
--   application behavior rather than a database constraint.

CREATE TABLE IF NOT EXISTS "ai_profile" (
    "id" text NOT NULL,
    "customer_id" text NOT NULL,
    "height" numeric NULL,
    "weight" numeric NULL,
    "base_body_image_url" text NULL,
    "raw_height" jsonb NULL,
    "raw_weight" jsonb NULL,
    "gender" text NULL,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    "deleted_at" timestamptz NULL,
    CONSTRAINT "ai_profile_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "IDX_ai_profile_deleted_at"
ON "ai_profile" ("deleted_at")
WHERE "deleted_at" IS NULL;

COMMENT ON TABLE "ai_profile" IS
'Custom Medusa module table for user AI profile data. customer_id is a logical reference to Medusa customer/auth actor.';

COMMENT ON COLUMN "ai_profile"."raw_height" IS
'Generated by Medusa bigNumber handling for height.';

COMMENT ON COLUMN "ai_profile"."raw_weight" IS
'Generated by Medusa bigNumber handling for weight.';

-- =====================================================================
-- 2. USER CLOSET ITEM
-- =====================================================================
-- Used by:
--   apps/api-medusa/src/api/v1/user/garments/route.ts
--   apps/api-medusa/src/api/v1/user/garments/[id]/route.ts
--   apps/api-medusa/src/api/v1/user/garments/vton-result/route.ts
--   apps/api-medusa/src/api/v1/user/assets/route.ts
--
-- Queue integration:
--   Created/deleted closet items publish messages to closet_metadata_sync.
--   The AI service mirrors searchable records into LanceDB table closet_vector.

CREATE TABLE IF NOT EXISTS "user_closet_item" (
    "id" text NOT NULL,
    "customer_id" text NOT NULL,
    "image_url" text NOT NULL,
    "category" text NOT NULL,
    "metadata" jsonb NULL,
    "vector_status" text NOT NULL DEFAULT 'pending',
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    "deleted_at" timestamptz NULL,
    CONSTRAINT "user_closet_item_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "IDX_user_closet_item_deleted_at"
ON "user_closet_item" ("deleted_at")
WHERE "deleted_at" IS NULL;

COMMENT ON TABLE "user_closet_item" IS
'Custom Medusa module table for personal wardrobe assets and saved VTON results.';

COMMENT ON COLUMN "user_closet_item"."vector_status" IS
'Application status for LanceDB synchronization, for example pending or not_applicable.';

-- =====================================================================
-- 3. STYLIST SESSION
-- =====================================================================
-- Used by:
--   apps/api-medusa/src/api/v1/stylist/search/route.ts
--   apps/api-medusa/src/api/v1/stylist/sessions/route.ts
--
-- Behavior:
--   Each successful AI Stylist query creates a stylist_session row. The
--   reasoning column currently stores a compact summary, usually generated
--   from outfit option titles.

CREATE TABLE IF NOT EXISTS "stylist_session" (
    "id" text NOT NULL,
    "customer_id" text NOT NULL,
    "prompt" text NOT NULL,
    "reasoning" text NULL,
    "status" text NOT NULL DEFAULT 'processing',
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    "deleted_at" timestamptz NULL,
    CONSTRAINT "stylist_session_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "IDX_stylist_session_deleted_at"
ON "stylist_session" ("deleted_at")
WHERE "deleted_at" IS NULL;

COMMENT ON TABLE "stylist_session" IS
'Custom Medusa module table for AI Stylist conversations and generated outfit sessions.';

-- =====================================================================
-- 4. STYLIST SESSION ITEM
-- =====================================================================
-- Used by:
--   apps/api-medusa/src/api/v1/stylist/search/route.ts
--
-- Physical relationship:
--   stylist_session_item.session_id references stylist_session.id.
--
-- Logical references:
--   product_id points to a Medusa product id for store products. The code only
--   attempts to persist valid store products here because product_id is not
--   nullable. Closet items are hydrated for the UI but are not persisted as
--   first-class closet foreign keys in this table.

CREATE TABLE IF NOT EXISTS "stylist_session_item" (
    "id" text NOT NULL,
    "session_id" text NOT NULL,
    "product_id" text NOT NULL,
    "replaces_item_id" text NULL,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    "deleted_at" timestamptz NULL,
    CONSTRAINT "stylist_session_item_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "IDX_stylist_session_item_session_id"
ON "stylist_session_item" ("session_id")
WHERE "deleted_at" IS NULL;

CREATE INDEX IF NOT EXISTS "IDX_stylist_session_item_deleted_at"
ON "stylist_session_item" ("deleted_at")
WHERE "deleted_at" IS NULL;

ALTER TABLE IF EXISTS "stylist_session_item"
ADD CONSTRAINT "stylist_session_item_session_id_foreign"
FOREIGN KEY ("session_id")
REFERENCES "stylist_session" ("id")
ON UPDATE CASCADE;

COMMENT ON TABLE "stylist_session_item" IS
'Custom Medusa module table for store products selected in an AI Stylist session.';

COMMENT ON COLUMN "stylist_session_item"."product_id" IS
'Logical reference to a Medusa product id. No physical FK is declared by the module migration.';

COMMENT ON COLUMN "stylist_session_item"."replaces_item_id" IS
'Logical id of the item being replaced. The current MVP does not enforce a physical FK.';

-- =====================================================================
-- 5. VTON JOB
-- =====================================================================
-- Used by:
--   apps/api-medusa/src/api/v1/vton/jobs/route.ts
--   apps/api-medusa/src/modules/ai-personalization/loaders/vision-consumer.ts
--   apps/api-medusa/src/services/queue/VisionOrchestrator.ts
--
-- Queue integration:
--   Medusa publishes jobs to ai_vision_jobs. The AI service publishes results
--   to ai_vision_results. The Medusa vision consumer updates this table and
--   broadcasts the final payload through SSE.
--
-- Implementation note:
--   parent_job_id is a logical self-reference used to chain multi-step local
--   VTON jobs. It is stored as text and does not have a physical FK.
--
-- MVP note:
--   During multi-step local VTON, the next garment URL is temporarily stored
--   in error_message before the child job is dispatched. A production schema
--   should replace this with a metadata JSONB column or a dedicated job input
--   table.

CREATE TABLE IF NOT EXISTS "vton_job" (
    "id" text NOT NULL,
    "customer_id" text NOT NULL,
    "parent_job_id" text NULL,
    "step" text NULL,
    "status" text NOT NULL DEFAULT 'pending',
    "result_image_url" text NULL,
    "error_message" text NULL,
    "retry_count" integer NOT NULL DEFAULT 0,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    "deleted_at" timestamptz NULL,
    CONSTRAINT "vton_job_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "IDX_vton_job_deleted_at"
ON "vton_job" ("deleted_at")
WHERE "deleted_at" IS NULL;

COMMENT ON TABLE "vton_job" IS
'Custom Medusa module table for asynchronous Virtual Try-On jobs.';

COMMENT ON COLUMN "vton_job"."parent_job_id" IS
'Logical self-reference used by the VTON orchestrator for multi-step local try-on.';

COMMENT ON COLUMN "vton_job"."error_message" IS
'Stores errors. In the current MVP, it is also temporarily used to hold the next garment URL for chained local jobs.';

-- =====================================================================
-- 6. LANCEDB VECTOR TABLES
-- =====================================================================
-- The following tables are not PostgreSQL tables. They are LanceDB/PyArrow
-- schemas defined in apps/ai-service/src/database/schema.py and are listed
-- here as documentation to keep the relational and vector stores synchronized.
--
-- products_vector:
--   product_id: string
--   vector: list<float32>[512]
--   category: string
--   gender: string
--   color: string
--   price: float64
--   in_stock: bool
--   style: list<string>
--   occasion: list<string>
--   material: string
--   name: string
--   image_url: string
--
-- closet_vector:
--   id: string
--   user_id: string
--   vector: list<float32>[512]
--   category: string
--   color: string
--   pattern: string
--   style: list<string>
--   material: string
--   image_url: string

-- =====================================================================
-- 7. LOGICAL MEDUSA CORE REFERENCES
-- =====================================================================
-- These names are used by the application code but are managed by MedusaJS:
--
--   customer/auth actor:
--     ai_profile.customer_id
--     user_closet_item.customer_id
--     stylist_session.customer_id
--     vton_job.customer_id
--
--   product:
--     stylist_session_item.product_id
--     stylist_session_item.replaces_item_id
--     products_vector.product_id in LanceDB
--
-- Do not add physical foreign keys here unless the custom Medusa module and
-- migrations are updated accordingly.
